name: test

on: push

jobs:
 Hello:
  name: first test
  runs-on: ubuntu-latest
  steps:
    - name: copy repo
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: testing
      run: go test ./... -v

