name: test

on: push

jobs:
 Hello:
  name: first test
  runs-on: ubuntu-latest
  steps:
    - name: copy repo
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: add to dockerhub
      uses: docker/build-push-actions@v5
      with:
        context: .
        push: true
        tags: sergeibalabaev/summator:latest 